stages:
  - build

build:
  stage: build
  image: gradle:6.0-jdk13
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:18.09-dind
      command: ["--insecure-registry=registry.balcia.com"]
  script:
    - ./gradlew jib --image=$CI_REGISTRY_IMAGE -Djib.allowInsecureRegistries=true -Djib.from.image=openjdk:13-jdk-alpine
  except:
    - tags
