version: '3'

services:
  server:
    image: registry.balcia.com/balcia_dev/java/spring-ws
    ports:
      - '8180:8080'
    environment:
      - MYSQL_HOST=db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root_234
