version: '3'

services:
  server:
    image: registry.balcia.com/balcia_dev/java/spring-ws
    ports:
      - '8180:8080'
    environment:
      - MYSQL_HOST=db

  keycloak:
    image: quay.io/keycloak/keycloak:6.0.0
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin_234
    ports:
      - '8280:8080'

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root_234
