version: '3'

services:
#  server:
#    build:
#      context: .
#    image: registry.balcia.com/balcia_dev/java/quarkus-ws
#    ports:
#      - '8080:8080'
#      - '8778:8778'
#      - '9779:9779'
#    environment:
#      - POSTGRES_PASSWORD=postgres_234
#      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
#      - QUARKUS_PROFILE=dev

  keycloak:
    image: quay.io/keycloak/keycloak:7.0.0
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin_234
#      - KEYCLOAK_IMPORT=/tmp/balcia-realm.json
    ports:
      - '8180:8080'

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root_234
